config/routes.rb
ArtzibitDev::Application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    mailers: "users/mailer"
  }

  get "home", to: 'page#home', as: 'home'
  get "about", to: 'page#about', as: 'about'
  get "terms_of_service", to: 'page#terms_of_service', as: 'terms_of_service'
  get "faq", to: 'page#faq', as: 'faq'
  get "contact", to: 'page#contact', as: 'contact'
  get "favorites", to: 'page#favorites', as: 'favorites'
  get "cart", to: 'page#cart', as: 'cart'
  get "profile", to: 'page#profile', as: 'profile'
  get "manual_payment", to: 'page#manual_payment', as: 'manual_payment'

  resources :charges
  resources :test_users, only: [:create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # match "/auth/:provider/callback" => "sessions#create"
  # match "/signout" => "sessions#destroy", :as => :signout
  # match "/signin" => "sessions#new", :as => :signin
  resources :users, only: [:show]
  resources :artwork_styles, only: [:index]
  resources :orders, only: [:show]
  resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
    :destroy] do
    collection do
      get "crop/:id", action: "crop", as: "crop"
      get "reprocess/:id", action: "reprocess", as: "reprocess"
    end
  end
  resources :artwork_approval_dtls, only: [:show]

  resources :products, only: [:index, :show]

  # ==================================================== #
  # =============  API Routes - Version 1  ============= #
  # ==================================================== #
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        scope "/users" do
          resources :registrations, only: [:create, :update, :destroy]
          resources :sessions, only: [:create, :destroy]
          resources :passwords, only: [:create]
        end
        get "current_user_details", to: "users#current_user_details", as: "current_user_details"
      end
      resources :users, only: [:show]
      resources :size_options, only: [:index]
      resources :categories, only: [:index]
      resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
        :destroy]
      resources :artists, only: [:index]
      resources :user_favorites, only: [:index, :create, :update]
      resources :artwork_styles, only: [:index]
      resources :sizes, only: [:index]
      resources :event_batches, only: [:index, :show]
      resources :user_checked_ins, only: [:create]
      resources :carts, only: [:index, :show, :create, :update]
      resources :users, only: [:update]
      resources :orders, only: [:index, :show]
      resources :user_shipping_details, only: [:index, :create, :destroy, :update]
      resources :filters, only: [:index]
      resources :user_bank_details, only: [:index, :create]
      resources :artwork_markers, only: [:create]
      resources :user_views, only: [:create]
      resources :user_launch_app_counters, only: [:create]
      resources :user_app_tracking_logs, only: [:create]
      resources :user_activation_codes, only: [:create]
    end
  end

  # ==================================================== #
  # =============  API Routes - Version 2  ============= #
  # ==================================================== #

  namespace :api, defaults: {format: :json} do
    namespace :v2 do
      devise_scope :user do
        scope "/users" do
          resources :registrations, only: [:create, :update, :destroy]
          resources :sessions, only: [:create, :destroy]
          resources :passwords, only: [:create]
        end
      end
      resources :categories, only: [:index]
      resources :artworks
      resources :filters, only: [:index]
      resources :user_favorites, only: [:index, :create]
      resources :cart_items, only: [:index, :create, :update, :destroy]
      resources :user_bank_details, only: [:index, :create, :update]
      resources :user_shipping_details, only: [:index, :create, :update,
        :destroy]
      resources :payments, only: [:create]
      resources :orders, only: [:index, :show]
      resources :supports, only: [:create]
      resources :carts, only: [:create]
      resources :web_repositories, only: [:index, :show]
      resources :reviews, only: [:index, :show, :create]
    end
  end
  root :to => "page#home"
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_many :artists

  def v1_format
    {
      id: id,
      name: name
    }
  end
end

app/views/shared/_breadcrumbs.html.erb
<div class="row mb-20 hidden">
    <div class="col-md-12">
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Library</a></li>
            <li class="active">Data</li>
        </ol>
    </div>
</div>

app/views/shared/_file_requirements.html.erb
<div class="col-md-8 col-md-offset-1">
  <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2 col-xs-10
    col-xs-offset-2">
    <div class="requirements">
      <div class="row">
        <div class="requirement-header">
          <h4> FILE REQUIREMENTS: </h4>
        </div>
        <div class="requirement-body">
          <ul>
            <li> High Res JPEG files </li>
            <li> RGB color mode</li>
            <li> At least 2500px at the smallest side </li>
            <li> Image resolution at 300dpi </li>
            <li> File size should not exceed 75mb</li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="requirement-header">
          <h4> THINGS TO REMEMBER: </h4>
        </div>
        <div class="requirement-body">
          <ul>
            <li> Each artwork will undergo an approval process from the Artzibit curators. This usually takes 2 – 3 days. </li>
            <li> Only one image upload is allowed for each artwork. If your image is still in pending status, you can still change images but this will reset the approval process.</li>
            <li> Artwork ratio should be 1:1 for square images or 3:2 for rectangle images.</li>
            <li> Try to keep important details away from the borders of the image. </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% unless key == "notice" %>
    <div id="page-mask" %>
    <%= content_tag :div, value, id: "popup_#{key}", class: "col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-4" do %>
      <span class="close close-flash"> <%= image_tag "close.png", onclick: "closeButton();" %></span>
      <span> <%= flash["#{key}"]%> </span>
    <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash_not_popup.html.erb
<% flash.each do |key, value| %>
  <%= content_tag :div, value, id: "#{key}" do %>
    <span> <%= flash["#{key}"]%> </span>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="col-xs-12 footer mt-40">
	<div class="container-fluid">
		<div class="row ">
			<div class="col-md-4 p-0 ta-center-on-sm m-b-10">
				&copy; 2017 Artzibit
			</div>
			<div class="col-md-8 p-0  text-right ta-center-on-sm m-b-10">
				<a href="<%= about_path %>" class="menu-item">About Artzibit</a>
				<a href="<%= terms_of_service_path %>" class="menu-item">Terms of Service</a>
				<a href="<%= faq_path %>" class="menu-item">FAQs</a>
				<a href="<%= contact_path %>" class="menu-item">Contact</a>
			</div>
		</div>
	</div>
</div>

app/views/shared/_navbar.html.erb
<!-- START HEADER AREA -->
<header class="header-area header-wrapper" ng-controller="HeaderController as header">
    <!-- header-middle-area -->
    <div id="sticky-header" class="header-middle-area bg-white">
        <div class="container-fluid">
            <div class="full-width-mega-dropdown">
                <div class="row">
                    <!-- logo -->
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        <div class="logo">
                            <%= link_to root_path do %>
                                <%= image_tag "black_logo.png", alt: "Artzibit" , class: "img-responsive center-block" %>
                            <% end %>
                        </div>
                    </div>
                    <!-- primary-menu -->
                    <div class="col-md-4 col-sm-12">
                      <form action="<%= products_path %>">
                        <div class="input-group search-input">
                          <input type="text" name="keyword" class="form-control" placeholder="Search" ng-model="header.keyword">
                          <span class="input-group-btn">
                            <button ng-disabled="!header.keyword" type="submit" class="btn-sumbmit btn btn-default" type="button"><i class="zmdi zmdi-search zmdi-hc-lg"></i></button>
                          </span>
                        </div><!-- /input-group -->
                      </form>
                    </div>
                    <div class="col-md-6 hidden-sm hidden-xs">
                        

                        <nav id="primary-menu f-right">
                          <ul class="main-menu text-right">

                              <li>
                                  <a href="javascript:void(0)">Browse Artwork</a>
                                  <ul class="dropdwn">
                                    <li ng-repeat="item in categories.values"><a href="<%= products_path %>?category_ids={{item.id}}">{{item.name}}</a></li>
                                  </ul>
                              </li>
                              <% if current_user.blank? %>
                              <li>
                                <%= link_to "Sign Up", new_registration_path(:user), class: "#{navbar_white_link_active(controller_name, action_name,
                                'sign_up')}" %>
                              </li>
                              <li>
                                <%= link_to "Sign In", new_session_path(:user), class: "#{navbar_white_link_active(controller_name, action_name, 'sign_in')}" %>
                              </li>
                              <% else %>

                              <li>
                                  
                                  <a href="#" class="inline-block">
                                    <span class="truncate inline-block valign-m name"> <%= current_user['first_name'] %> <%= current_user['last_name'] %> </span>
                                    <span class="caret inline-block  valign-m" style= "color:<%=@color%>;"></span>
                                  </a>
                                  <ul class="dropdwn">
                                    <li>
                                      <%= link_to profile_path, style: "color:#{@color};" do %>
                                        My Profile
                                      <% end %>
                                    </li>
                                    <li>
                                      <%= link_to new_artwork_path, style: "color:#{@color};" do %>
                                        Upload Artwork
                                      <% end %>
                                    </li>
                                    <li>
                                      <%= link_to destroy_user_session_path, method: "delete", style: "color:#{@color};" do %>
                                        Sign Out
                                      <% end %>
                                    </li>
                                  </ul>
                                  <div class="initial ml-5">
                                      <span class="text"><%= current_user.try(:first_name) ? current_user.first_name[0] : ''  %><%= current_user.try(:last_name) ? current_user.last_name[0] : ''  %></span>
                                  </div>
                              </li>
                              <% end %>
                              
                              <li  class="total-cart-show">
                                  <a href="javascript:void(0)">
                                      <i class="zmdi zmdi-shopping-cart zmdi-hc-lg cart-toggler"></i>
                                  </a>

                                  <div class="total-cart-in p-0">
                                      <ul class="cart-container">
                                          <div class="block text-center" ng-if="!cart_items">
                                            <i class="fa fa-spinner fa-spin fa-2x color-gray2 loading-font"></i>
                                          </div>
                                          <li ng-if="cart_items.items.length < 1 || (!cart_items.items && cart_items)">
                                              <div class="top-cart-inner your-cart">
                                                  <p>Looks like you have nothing here</p>
                                                  <p>Add artwork to your cart and we'll take care of everything when you check out</p>
                                                  <a href="<%= products_path %>" class="button button-black text-center w-100" tabindex="-1">
                                                      <span class="text-uppercase w-100">Start Shopping</span>
                                                  </a>
                                              </div>
                                          </li>
                                          <li ng-if="cart_items.items.length > 0">
                                              <div class="top-cart-inner your-cart">
                                                  <h5 class="text-capitalize">Your Cart</h5>
                                              </div>
                                          </li>
                                          <li> 
                                            <!-- 
                                            <div class="block text-center" ng-if="cart_items.items.length < 1 || (!cart_items.items && cart_items)">
                                              <p class="pt-10">No items found here</p>
                                            </div> -->
                                              <div class="total-cart-pro" ng-if="cart_items.items.length > 0">
                                                  <!-- single-cart -->
                                                  <div class="single-cart clearfix" ng-repeat="item in cart_items.items">
                                                      <div class="cart-img col-xs-4 text-left">
                                                              <img ng-src="{{item.image}}" class="img-responsive">
                                                      </div>
                                                      <div class="cart-info col-xs-8 text-right">
                                                        <strong class="block">{{item.name}}</strong>
                                                        <small class="block"><i>{{item.artist_name}}</i></small>
                                                        <small class="block">Quantity: {{item.quantity}}</small>
                                                          

                                                          <p>
                                                              {{item.price  || 0 | currency}}
                                                          </p>
                                                      </div>
                                                  </div>
                                                  <!-- single-cart -->
                                              </div>
                                          </li>
                                          <li ng-if="cart_items.items.length > 0">
                                            <div class="block item-details-block">
                                              <div class="col-xs-6 text-left"><strong>Shipping Fee</strong></div>
                                              <div class="col-xs-6 p-0 text-right">{{cart_items.shipping_fee || 0  || 0 | currency }}</div>
                                            </div>
                                          </li>
                                          <li ng-if="cart_items.items.length > 0">
                                            <div class="block item-details-block">
                                              <div class="col-xs-6 text-left"><strong>Total</strong></div>
                                              <div class="col-xs-6 p-0 text-right">{{cart_items.total || 0  || 0 | currency }}</div>
                                            </div>
                                          </li>
                                          <li ng-if="cart_items.items.length > 0">
                                              <div class="top-cart-inner check-out">
                                                  <h4 class="text-uppercase">
                                                      <a href="<%= cart_path %>">Check out</a>
                                                  </h4>
                                              </div>
                                          </li>
                                      </ul>
                                  </div>
                              </li>
                              <li>
                                  <a href="<%= favorites_path %>">
                                      <i class="zmdi zmdi-star-outline zmdi-hc-lg"></i>
                                  </a>
                              </li>
                              <!-- <li>
                                  <a href="#">
                                      <i class="zmdi zmdi-search zmdi-hc-lg"></i>
                                  </a>
                              </li> -->
                          </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- END HEADER AREA -->

<!-- START MOBILE MENU AREA -->
<div class="mobile-menu-area hidden-lg hidden-md">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="mobile-menu">
                    <nav id="dropdown">
                       <ul>
                         <li><a href="<%= products_path %>">Browse Artwork</a></li>
                            <% if current_user.blank? %>
                              <li>
                                <%= link_to "Sign Up", new_registration_path(:user), class: "#{navbar_white_link_active(controller_name, action_name,
                                'sign_up')}" %>
                              </li>
                              <li>
                                <%= link_to "Sign In", new_session_path(:user), class: "#{navbar_white_link_active(controller_name, action_name, 'sign_in')}" %>
                              </li>
                            <% else %>
                              <li>
                                  <a href="#" class="inline-block"><%= current_user['name'] || 'User' %> </a>
                                  <ul>
                                    <li>
                                      <%= link_to profile_path, style: "color:#{@color};" do %>
                                        My Profile
                                      <% end %>
                                    </li>
                                    <li>
                                      <%= link_to new_artwork_path, style: "color:#{@color};" do %>
                                        Upload Artwork
                                      <% end %>
                                    </li>
                                    <li>
                                      <%= link_to destroy_user_session_path, method: "delete", style: "color:#{@color};" do %>
                                        Sign Out
                                      <% end %>
                                    </li>
                                  </ul>
                              </li>
                              
                            <% end %>
                                <li>
                                    <a href="<%= cart_path %>">
                                        <i class="zmdi zmdi-shopping-cart zmdi-hc-lg"></i>
                                        Cart
                                    </a>
                                </li>
                                <li>
                                    <a href="<%= favorites_path %>">
                                        <i class="zmdi zmdi-star-outline zmdi-hc-lg"></i>
                                        Favourites
                                    </a>
                                </li>
                       </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END MOBILE MENU AREA -->


<script type="text/javascript">
  function display_sign_in() {
    sign_in = document.getElementById("page-mask-signin");
    sign_form = document.getElementById("new_user_form");
    sign_in.style.display = "block";
    sign_form.style.display = "block";
  }
</script>

app/views/shared/_navbar_white.html.erb
<nav class="navbar navbar-white navbar-toggleable-md bg-inverse navbar-static-top navbar-default">  
    <div class="container">       
        <h1 class="logo">
            <%= link_to root_path, class: "navbar-brand" do %>
               <%= image_tag "black_logo.png", height: "130%" %>
            <% end %>
        </h1><!--//logo-->
        <nav class="main-nav navbar-right" role="navigation">
            <div class="navbar-header">
                <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button><!--//nav-toggle-->
            </div><!--//navbar-header-->
            <div id="navbar-collapse" class="navbar-collapse collapse">
               <ul class="nav navbar-nav navbar-right">
              <% if current_user.blank? %>
                <li>
                  <%= link_to "Sign Up", new_registration_path(:user), style: "color:#{@color};",
                  class: "#{navbar_white_link_active(controller_name, action_name,
                  'sign_up')}" %>
                </li>
                <li>
                  <%= link_to "Sign In", new_session_path(:user), style: "color:#{@color};",
                    class: "#{navbar_white_link_active(controller_name, action_name, 'sign_in')}" %>
                </li>
              <% else %>
               <li class="dropdown">
                  <a href="#" class="dropdown-toggle <%= navbar_white_link_active(controller_name,
                    action_name, 'profile') %>"
                    data-toggle="dropdown"
                    role="button" aria-haspopup="true" aria-expanded="false"
                    style= "color:<%=@color%>;background-color:white;">
                    PROFILE
                      <span class="caret" style= "color:<%=@color%>;"></span>
                  </a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to artworks_path, style: "color:#{@color};" do %>
                        MY ARTWORKS
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_user_registration_path, style: "color:#{@color};" do %>
                        EDIT PROFILE
                      <% end %>
                    </li>
                    <li>
                      <%= link_to destroy_user_session_path, method: "delete", style: "color:#{@color};" do %>
                        SIGN OUT
                      <% end %>
                    </li>
                  </ul>
                </li>
              <% end %>
          </ul>
            </div><!--//navabr-collapse-->
        </nav><!--//main-nav-->                     
    </div><!--//container-->
</nav><!--//header-->

app/views/shared/_product_item.html.erb
<!-- product-item start -->
<div class="product-item" ng-class="{'product-item-with-options': my_artwork_page}">
  <div class="product-img">
    <a href="<%= products_path %>/{{product.id}}">
      <div class="img-con">
        <img class="img-responsive" ng-src="{{product.image}}" alt=""/>
      </div>
    </a>
  </div>
  <div class="product-info">
    <div class="row m-0">
      <div class="col-xs-8 p-0">
        <h6 class="product-title">
          <a href="<%= products_path %>/{{product.id}}">{{product.name}}</a>
        </h6>
        <h7 class="product-owner">
          <a href="<%= products_path %>?artist_ids={{product.artist_id}}">{{ product.artist_name }}</a>
        </h7>
      </div>
      <div class="col-xs-4  p-0 text-right v-align-t-childs mt-10">
        <a href="javascript:void(0)" favorite-toggle-button>
          <i ng-if="product.loading" class="fa fa-spin fa-spinner"></i>
           <i ng-if="!product.loading"
              class="fa fa-star-outline-sm" 
              ng-class="product.favorited ? 'fa-star-sm' : 'fa-star-outline-sm'"
              uib-tooltip="{{product.favorited ? 'Remove from favorites?': 'Add to favorites?'}}">
            </i>
       </a>
        <span class="fav-counts">{{product.favorites_count}}</span>
      </div>
    </div>
    <div ng-if="product.artist_id == current_user_id && my_artwork_page"  class="block product-options">
      <span>{{product.created_at}}</span>
      <span class="text-right f-right">
        <a href="<%= artworks_path %>/{{product.id}}/edit" class="control"><i class="zmdi zmdi-edit"></i></a>
        <a href="javascript:void(0)" ng-click="my_artworks.destroyArtworkDetails(product, $idx)" class="control"><i class="zmdi zmdi-close"></i></a>
      </span>
    </div>
  </div>
</div>
<!-- product-item end -->